FROM python:3.14-slim

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY app.py /app/app.py

ENV PYTHONUNBUFFERED=1
EXPOSE 8080

CMD ["python", "app.py"]
